---
- name: "Finalize role | {{ _title_pfx }}"
  become: true
  tags: always
  block:
    - name: "Header | Finish | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "---------------------------------- FINISH ----------------------------------"

    - name: "Clean tmp files and directories | Finish | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "{{ example__tmp_dir }}"
        state: absent
