---
- name: "Initialize role | {{ _title_pfx }}"
  delegate_to: "{{ ansible_hostname | default('localhost', true) }}"
  become: true
  tags: always
  block:
    - name: "Display title | Init | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg:
          - "######################################################################################"
          - "##                                   EXAMPLE ROLE                                   ##"
          - "######################################################################################"

    - name: "Ensure tmp directory exists | Init | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "{{ example__tmp_dir }}"
        state: directory
        mode: "0755"
