---
- name: "Role Example | {{ _title_pfx }}"
  become: true
  block:
    - name: "Initialize role | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: init.yml
      tags: [always]

    - name: "Task for example role | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "------- This is an task example role -------"

    - name: "Finalize role | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: finish.yml
      tags: [always]
